repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.7.4'
  hooks:
    - id: ruff
- repo: https://github.com/psf/black
  rev: '24.10.0'
  hooks:
  - id: black
    language_version: python3.10